from allennlp_semparse.predictors.atis_parser import AtisParserPredictor
from allennlp_semparse.predictors.nlvr_parser import NlvrParserPredictor
from allennlp_semparse.predictors.quarel_parser import QuarelParserPredictor
from allennlp_semparse.predictors.wikitables_parser import WikiTablesParserPredictor
